### ISSUE TITLE
Feature Request: provide a package access to the Python script

### ISSUE THREAD

**Issue by rhuygen** [IvS-KULeuven/PlatoSim3#548]
All the Python code for PlatoSim3 is packed in one directory called `python` which is located at the root of the project. There is no specific package called 'platosim' under this location which makes it difficult to combine the PlatoSim3 Python code with other projects.

I propose to put the different modules in the `python` folder in a package called `platosim` such that they can be used and imported in other projects without contaminating the local namespace.

```
Project
  |
  +----- python
          |
          +----- platosim
                     |
                     +----- h5.py
                     +----- noise.py
                     +----- other python modules...
```

**Comment by Dries-Seynaeve** [comment]
Hello Rik. I implemented this feature. It is now possible to import modules through the platosim package. e.g.

`from platosim import simulatuation`

or 

`imort platosim.simulation`

or 

`from platosim.simulation import Simulation`.

**Comment by rhuygen** [comment]
Thanks Dries!
Could it be that you forgot platophot.py or is there a reason why it's still in the python folder?

**Comment by Dries-Seynaeve** [comment]
Hello Rik. 

This package has become obsolete. This has already been implemented from within PlatoSIM, so I should have removed that file. 
I have done so in my last push.
